SAT nodes=1218463 time=0.18s S=31 T=911
13 24
WW.....WWW...
WWW....WWW...
WWWW....WW...
WWWW.........
.WWW.........
..........B..
..........BB.
..........BBB
....B.....BBB
....BB.....BB
....BBB.....B
....BBB......
....BBB......
