/* bnb.c — fast port of bnb.py (exact branch-and-bound for peaceable
 * queens in the line-labeling formulation).
 *
 * Semantics are deliberately identical to bnb.py: same canonical form
 * (row 0 white), same pruning bounds (product, cell, family-sum), same
 * branching rule (first free diagonal maximizing min(live-white,
 * live-black), dp family scanned before dm, ascending index, strict >),
 * same color order (W then B), same node counting (one per (S,T) pair
 * passing the product prunes, one per DFS entry).  Node counts of the
 * two implementations on the same instance must be EQUAL; this is the
 * cross-verification used in NOTE.md.
 *
 * The only differences are representational (incrementally maintained
 * per-diagonal live counters instead of rescans — same values).
 *
 * Usage: bnb n m [stride offset]
 *   stride/offset split the outer row-set loop for parallel runs:
 *   worker handles the k-th odd S with k % stride == offset.
 * Exit: prints "STATUS nodes=N time=T"; SAT also prints witness grid.
 *
 * Build: gcc -O2 -march=native -o bnb bnb.c
 *
 * SYM16 variant (build with -DSYM16 -o bnb_sym): instead of the odd-S
 * canonical form, enumerate ALL (S,T) and process only the pairs that
 * are lexicographically minimal (as the 32-bit key S<<16|T) among their
 * 16 images under the group generated by row reversal, column
 * reversal, transpose, and color swap — all of which are symmetries of
 * the problem (they permute lines and preserve peaceability).  Node
 * counts are NOT comparable with the plain build; verdicts must agree.
 * Stride splitting applies to the S loop (all S, not odd S).
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define MAXN 24
#define MAXD (2 * MAXN - 1)
#define MAXC (MAXN * MAXN)

static int n, m, N2;
static long long nodes = 0, node_limit = 0;

/* per-(S,T) cell data */
static int wnum, bnum;
static int wr[MAXC], wc[MAXC], br_[MAXC], bc_[MAXC];
static int wdp[MAXC], wdm[MAXC], bdp[MAXC], bdm[MAXC];
static unsigned char walive[MAXC], balive[MAXC];
static int wcount, bcount;

/* per-diagonal cell lists (indices into cell arrays) */
static int wby_dp[MAXD][MAXN], wby_dp_n[MAXD];
static int wby_dm[MAXD][MAXN], wby_dm_n[MAXD];
static int bby_dp[MAXD][MAXN], bby_dp_n[MAXD];
static int bby_dm[MAXD][MAXN], bby_dm_n[MAXD];

/* live counters per diagonal per family per color */
static int aw_dp[MAXD], aw_dm[MAXD], ab_dp[MAXD], ab_dm[MAXD];

/* labels: 0 free, 1 W, 2 B */
static unsigned char dplab[MAXD], dmlab[MAXD];

/* witness snapshot, captured AT the SAT leaf (the live sets are restored
 * during unwinding, so reading them at the top level shows the full
 * candidate grids — a bug the independent checker caught on 2026-08-17) */
static unsigned char wit_w[MAXC], wit_b[MAXC];

static int undo_stack[1 << 20], undo_top;

static int kill_cells(int fam_is_dp, int idx, int color)
{
    /* label diagonal; kill live cells of the excluded color; returns
     * count pushed on undo stack */
    int pushed = 0;
    if (color == 2) { /* B kills white */
        int cnt = fam_is_dp ? wby_dp_n[idx] : wby_dm_n[idx];
        int *lst = fam_is_dp ? wby_dp[idx] : wby_dm[idx];
        for (int k = 0; k < cnt; k++) {
            int i = lst[k];
            if (walive[i]) {
                walive[i] = 0;
                wcount--;
                aw_dp[wdp[i]]--;
                aw_dm[wdm[i]]--;
                undo_stack[undo_top++] = i;
                pushed++;
            }
        }
    } else { /* W kills black */
        int cnt = fam_is_dp ? bby_dp_n[idx] : bby_dm_n[idx];
        int *lst = fam_is_dp ? bby_dp[idx] : bby_dm[idx];
        for (int k = 0; k < cnt; k++) {
            int i = lst[k];
            if (balive[i]) {
                balive[i] = 0;
                bcount--;
                ab_dp[bdp[i]]--;
                ab_dm[bdm[i]]--;
                undo_stack[undo_top++] = i;
                pushed++;
            }
        }
    }
    return pushed;
}

static void revive_cells(int color, int pushed)
{
    if (color == 2) {
        while (pushed--) {
            int i = undo_stack[--undo_top];
            walive[i] = 1;
            wcount++;
            aw_dp[wdp[i]]++;
            aw_dm[wdm[i]]++;
        }
    } else {
        while (pushed--) {
            int i = undo_stack[--undo_top];
            balive[i] = 1;
            bcount++;
            ab_dp[bdp[i]]++;
            ab_dm[bdm[i]]++;
        }
    }
}

static int family_sum_ok(void)
{
    int tot = 0;
    for (int i = 0; i < N2; i++) {
        int aw = aw_dp[i], ab = ab_dp[i];
        if (dplab[i] == 1) tot += aw;
        else if (dplab[i] == 2) tot += ab;
        else tot += aw >= ab ? aw : ab;
    }
    if (tot < 2 * m) return 0;
    tot = 0;
    for (int i = 0; i < N2; i++) {
        int aw = aw_dm[i], ab = ab_dm[i];
        if (dmlab[i] == 1) tot += aw;
        else if (dmlab[i] == 2) tot += ab;
        else tot += aw >= ab ? aw : ab;
    }
    return tot >= 2 * m;
}

/* returns 1 SAT, 0 UNSAT, -1 LIMIT */
static int dfs(void)
{
    nodes++;
    if (node_limit && nodes > node_limit) return -1;
    if (wcount < m || bcount < m) return 0;
    if (!family_sum_ok()) return 0;

    int best = -1, bfam = 0, bidx = -1;
    for (int i = 0; i < N2; i++) {
        if (dplab[i]) continue;
        int aw = aw_dp[i], ab = ab_dp[i];
        if (aw && ab) {
            int score = aw < ab ? aw : ab;
            if (score > best) { best = score; bfam = 1; bidx = i; }
        }
    }
    for (int i = 0; i < N2; i++) {
        if (dmlab[i]) continue;
        int aw = aw_dm[i], ab = ab_dm[i];
        if (aw && ab) {
            int score = aw < ab ? aw : ab;
            if (score > best) { best = score; bfam = 0; bidx = i; }
        }
    }
    if (best <= 0) {
        memcpy(wit_w, walive, wnum);
        memcpy(wit_b, balive, bnum);
        return 1;
    }

    unsigned char *lab = bfam ? dplab : dmlab;
    for (int color = 1; color <= 2; color++) {
        lab[bidx] = color;
        int pushed = kill_cells(bfam, bidx, color);
        int r = dfs();
        revive_cells(color, pushed);
        lab[bidx] = 0;
        if (r != 0) return r;
    }
    return 0;
}

static void print_witness(void)
{
    static char g[MAXN][MAXN + 1];
    for (int r = 0; r < n; r++) {
        memset(g[r], '.', n);
        g[r][n] = 0;
    }
    for (int i = 0; i < wnum; i++)
        if (wit_w[i]) g[wr[i]][wc[i]] = 'W';
    for (int i = 0; i < bnum; i++)
        if (wit_b[i]) g[br_[i]][bc_[i]] = 'B';
    printf("%d %d\n", n, m);
    for (int r = 0; r < n; r++) puts(g[r]);
}

int main(int argc, char **argv)
{
    if (argc < 3) { fprintf(stderr, "usage: bnb n m [stride offset]\n"); return 2; }
    n = atoi(argv[1]);
    m = atoi(argv[2]);
    long stride = 1, offset = 0;
    if (argc >= 5) { stride = atol(argv[3]); offset = atol(argv[4]); }
    N2 = 2 * n - 1;

    clock_t t0 = clock();
#ifdef SYM16
    long FULL = (1L << n) - 1;
    for (long S = 0; S <= FULL; S++) {
        if (S % stride != offset) continue;
        int rw = __builtin_popcountl(S);
        if ((long)rw * n < m || (long)(n - rw) * n < m) continue;
        long revS = 0;
        for (int i = 0; i < n; i++) if ((S >> i) & 1) revS |= 1L << (n - 1 - i);
        for (long T = 0; T <= FULL; T++) {
            int cw = __builtin_popcountl(T);
            if ((long)rw * cw < m || (long)(n - rw) * (n - cw) < m) continue;
            {
                long revT = 0;
                for (int i = 0; i < n; i++)
                    if ((T >> i) & 1) revT |= 1L << (n - 1 - i);
                long key = (S << n) | T, best = key;
                long as[2] = {S, revS}, bs[2] = {T, revT};
                for (int ai = 0; ai < 2; ai++)
                    for (int bi = 0; bi < 2; bi++) {
                        long A = as[ai], Bv = bs[bi];
                        long k1 = (A << n) | Bv;         /* D4: no swap */
                        long k2 = (Bv << n) | A;         /* transpose   */
                        long k3 = ((FULL ^ A) << n) | (FULL ^ Bv); /* +color */
                        long k4 = ((FULL ^ Bv) << n) | (FULL ^ A);
                        if (k1 < best) best = k1;
                        if (k2 < best) best = k2;
                        if (k3 < best) best = k3;
                        if (k4 < best) best = k4;
                    }
                if (best < key) continue;
            }
#else
    long odd_index = 0;
    for (long S = 1; S < (1L << n); S += 2, odd_index++) {
        if (odd_index % stride != offset) continue;
        int rw = __builtin_popcountl(S);
        if ((long)rw * n < m || (long)(n - rw) * n < m) continue;
        for (long T = 0; T < (1L << n); T++) {
            int cw = __builtin_popcountl(T);
            if ((long)rw * cw < m || (long)(n - rw) * (n - cw) < m) continue;
#endif
            nodes++;
            if (node_limit && nodes > node_limit) goto limit;

            wnum = bnum = 0;
            memset(wby_dp_n, 0, sizeof(int) * N2);
            memset(wby_dm_n, 0, sizeof(int) * N2);
            memset(bby_dp_n, 0, sizeof(int) * N2);
            memset(bby_dm_n, 0, sizeof(int) * N2);
            memset(aw_dp, 0, sizeof(int) * N2);
            memset(aw_dm, 0, sizeof(int) * N2);
            memset(ab_dp, 0, sizeof(int) * N2);
            memset(ab_dm, 0, sizeof(int) * N2);
            for (int r = 0; r < n; r++) {
                int rin = (S >> r) & 1;
                for (int c = 0; c < n; c++) {
                    int cin = (T >> c) & 1;
                    int s = r + c, d = r - c + n - 1;
                    if (rin && cin) {
                        wr[wnum] = r; wc[wnum] = c;
                        wdp[wnum] = s; wdm[wnum] = d;
                        walive[wnum] = 1;
                        wby_dp[s][wby_dp_n[s]++] = wnum;
                        wby_dm[d][wby_dm_n[d]++] = wnum;
                        aw_dp[s]++; aw_dm[d]++;
                        wnum++;
                    } else if (!rin && !cin) {
                        br_[bnum] = r; bc_[bnum] = c;
                        bdp[bnum] = s; bdm[bnum] = d;
                        balive[bnum] = 1;
                        bby_dp[s][bby_dp_n[s]++] = bnum;
                        bby_dm[d][bby_dm_n[d]++] = bnum;
                        ab_dp[s]++; ab_dm[d]++;
                        bnum++;
                    }
                }
            }
            wcount = wnum; bcount = bnum;
            memset(dplab, 0, N2);
            memset(dmlab, 0, N2);
            undo_top = 0;

            int r = dfs();
            if (r == 1) {
                double dt = (double)(clock() - t0) / CLOCKS_PER_SEC;
                printf("SAT nodes=%lld time=%.2fs S=%ld T=%ld\n",
                       nodes, dt, S, T);
                print_witness();
                return 10;
            }
            if (r == -1) goto limit;
        }
    }
    {
        double dt = (double)(clock() - t0) / CLOCKS_PER_SEC;
        printf("UNSAT nodes=%lld time=%.2fs\n", nodes, dt);
        return 20;
    }
limit:
    printf("LIMIT nodes=%lld\n", nodes);
    return 30;
}
