"""Result C6: the binary Pansiot in-class ansatz is empty near the
undirected threshold.

For n in 20..23, alpha = (n-1)/(n-2): exhaustive DFS over binary Pansiot
codewords (decodes have all (n-1)-windows rainbow), pruned by the exact
U-alpha+ checker on the decode.  Prints the maximal codeword length and the
maximal codewords; writes data/code_class_emptiness.txt.

python3 code_class.py
"""

import sys
import time

from urt import UInc, decode

sys.setrecursionlimit(100000)


def code_lang(n, num, den, maxlen, cap=3_000_000):
    inc = UInc(num, den, maxlen + n + 2)
    for ch in decode([], n):
        ok = inc.push(ch)
        assert ok
    counts = [0] * (maxlen + 1)
    nodes = 0
    state = [list(range(n))]
    bits = []
    maximal = []

    def rec():
        nonlocal nodes
        d = len(bits)
        counts[d] += 1
        extended = False
        if d < maxlen and nodes <= cap:
            st = state[-1]
            for b in (0, 1):
                nodes += 1
                if b == 0:
                    x = st[0]
                    ns = st[1 : n - 1] + [st[0], st[n - 1]]
                else:
                    x = st[n - 1]
                    ns = st[1 : n - 1] + [st[n - 1], st[0]]
                if inc.push(x):
                    bits.append(b)
                    state.append(ns)
                    rec()
                    bits.pop()
                    state.pop()
                    extended = True
                inc.pop()
        if not extended:
            maximal.append("".join(map(str, bits)))

    rec()
    died = next((d for d in range(maxlen + 1) if counts[d] == 0), None)
    return counts, died, nodes, maximal


if __name__ == "__main__":
    lines = []
    for n in (20, 21, 22, 23):
        num, den = n - 1, n - 2
        t0 = time.time()
        counts, died, nodes, maximal = code_lang(n, num, den, 60)
        dt = time.time() - t0
        assert died is not None and nodes <= 3_000_000
        longest = max(maximal, key=len)
        line = (f"n={n} alpha={num}/{den}: U-code-free binary words die at "
                f"{died} bits (max {died-1}), {nodes} nodes, exhaustive; "
                f"longest codeword(s) incl. '{longest}' [{dt:.2f}s]")
        print(line)
        lines.append(line)
    with open("data/code_class_emptiness.txt", "w") as f:
        f.write("# Result C6 — generated by code_class.py, 2026-08-18\n")
        f.write("\n".join(lines) + "\n")
