"""Result C1: exhaustive death certificates at the threshold exponent.

For k in 22..25, alpha = (k-1)/(k-2): canonical DFS over words of Sigma_k
avoiding undirected exponents >= alpha (non-strict mode).  The tree is tiny
and fully exhausted; prints max length and node count, and writes
data/lower_bound_certificates.txt.

python3 lower_bounds.py
"""

import sys
import time

from urt import UInc

sys.setrecursionlimit(100000)


def death_search(n, num, den, strict, maxdepth, cap=60_000_000):
    inc = UInc(num, den, maxdepth + 2, strict=strict)
    counts = [0] * (maxdepth + 1)
    nodes = 0
    word = []

    def rec(used):
        nonlocal nodes
        d = len(word)
        counts[d] += 1
        if d == maxdepth or nodes > cap:
            return
        for c in range(min(used + 1, n)):
            nodes += 1
            if inc.push(c):
                word.append(c)
                rec(used + 1 if c == used else used)
                word.pop()
            inc.pop()

    t0 = time.time()
    rec(0)
    dt = time.time() - t0
    died = next((d for d in range(maxdepth + 1) if counts[d] == 0), None)
    return died, nodes, dt, counts


if __name__ == "__main__":
    lines = []
    for k in (22, 23, 24, 25):
        num, den = k - 1, k - 2
        died, nodes, dt, counts = death_search(k, num, den, False, 120)
        assert died is not None and nodes <= 60_000_000
        line = (f"k={k} alpha={num}/{den} (non-strict): max U-alpha-free "
                f"length = {died-1} (= k+{died-1-k}), {nodes} nodes, "
                f"exhaustive [{dt:.2f}s]")
        print(line)
        lines.append(line)
    with open("data/lower_bound_certificates.txt", "w") as f:
        f.write("# Result C1 — generated by lower_bounds.py, 2026-08-18\n")
        f.write("\n".join(lines) + "\n")
