#!/usr/bin/env python3
"""Exact constants for the lemma layer of NOTE.md.  All sums are exact
Fractions over primes generated by sympy; nothing floating-point.

L1 (integrality classes): for a set of m distinct odd primes,
    T := sum 1/p_i - prod 1/p_i  (Giuga)   or   T' := sum + prod (Znam/PPN)
    can only be a positive integer k if the sum of the m smallest odd
    prime reciprocals exceeds k - 1/3 (crude) -- we emit the exact minimal
    m for sum > 2, so that k >= 2 forces m >= that constant.
L2 (forced 3): if 3 is not among the primes, sum 1/p over the m smallest
    odd primes >= 5 stays below 1 up to the emitted m, so an odd Giuga
    number with at most that many factors is divisible by 3.
L3 (same, all primes) for the even-side k >= 2 disposal.
"""
from fractions import Fraction

from sympy import nextprime


def first_sum_exceeding(target, start_prime, skip=()):
    s = Fraction(0)
    p = start_prime
    m = 0
    while s <= target:
        if p not in skip:
            s += Fraction(1, p)
            m += 1
        p = nextprime(p)
    return m, p, s


def last_below(target, start_prime, skip=()):
    """largest m with sum of m smallest admissible primes' reciprocals <= target"""
    m, p, s = first_sum_exceeding(target, start_prime, skip)
    return m - 1


def main():
    m2_odd, p, s = first_sum_exceeding(2, 3)
    print(f"L1(odd):  sum 1/p over the {m2_odd} smallest odd primes first "
          f"exceeds 2 (last prime < {p}); exact sum = {float(s):.6f}")
    print(f"          => an odd set with T or T' >= 2 has m >= {m2_odd}")

    m1_no3 = last_below(1, 5)
    print(f"L2: sum 1/p over the {m1_no3} smallest odd primes >= 5 is still "
          f"<= 1; the ({m1_no3 + 1})-th pushes past 1")
    print(f"          => an odd Giuga set (sum > 1) with m <= {m1_no3} "
          f"contains 3")

    m2_all, p2, s2 = first_sum_exceeding(2, 2)
    print(f"L3(all):  sum 1/p over the {m2_all} smallest primes first "
          f"exceeds 2 => any set with T or T' >= 2 has m >= {m2_all}")

    m1_odd = last_below(1, 3)
    print(f"L4: sum over the {m1_odd} smallest odd primes <= 1 "
          f"=> an odd Giuga set has m >= {m1_odd + 1}")


if __name__ == "__main__":
    main()
